-- =======================================================
-- Supabase Schema for Sari-Sari Store Ledger
-- =======================================================

-- 1. Create Tables
CREATE TABLE public.admins (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text UNIQUE NOT NULL,
    password text NOT NULL
);

CREATE TABLE public.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text NOT NULL,
    role text DEFAULT 'customer'
);

CREATE TABLE public.debts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint REFERENCES public.customers(id) ON DELETE CASCADE,
    item_name text NOT NULL,
    amount numeric NOT NULL,
    date date DEFAULT CURRENT_DATE,
    status text DEFAULT 'unpaid'
);

-- 2. Row Level Security (RLS)
-- For this simple app, we are enabling RLS but allowing public access.
-- In a real app, you would tie this to Supabase Auth.
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read admins" ON public.admins FOR SELECT USING (true);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read customers" ON public.customers FOR SELECT USING (true);
CREATE POLICY "Allow public insert customers" ON public.customers FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update customers" ON public.customers FOR UPDATE USING (true);

ALTER TABLE public.debts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read debts" ON public.debts FOR SELECT USING (true);
CREATE POLICY "Allow public insert debts" ON public.debts FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update debts" ON public.debts FOR UPDATE USING (true);

-- 3. Seed Default Admin
INSERT INTO public.admins (username, password) VALUES ('Diana', 'password123');
